version: '3.9'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo_server
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
